### ISSUE TITLE
Issues with the Card Class

### ISSUE THREAD

**Issue by KristinaCer** [marthagarman1/sdjflwakejrwoeiunweorn#5]
Setters and drawCard() method in the Card class seem not to be used at any point in the program? I'm not sure if I completely understand how Player and Card classes are connected. I can't see any direct references from the Card class to the Player class, but I may be wrong!

**Comment by marthagarman1** [comment]
I think you're right - these are not used and should be removed.

**Comment by porshiaa** [comment]
Okay, I've deleted those methods!
