### ISSUE TITLE
Writing Junit tests for an abstract class

### ISSUE THREAD

**Issue by KristinaCer** [marthagarman1/sdjflwakejrwoeiunweorn#7]
Not sure how to write Junit tests for Player class, heeeelp! 😆

**Comment by marthagarman1** [comment]
You can make an object that can call those methods: for example 
AIPlayer test1 = new AIPlayer(); 

test1.getDeck() //or whatever methods are in the player class 
because AIPlayer inherits, it can/will call methods in the player class
